# @package apps.code_editor
defaults:
  - default
welcome_message: "欢迎！祝您每日编程愉快！"

+filesystem:
  - type: file
    name: basic_imports.py
    content: |
      # 基础导入，用于数据处理和分析
      import numpy as np
      import pandas as pd
  - type: file
    name: untitled_c.c
    content: |
      # 非常简单的 C 程序，什么也不做
      #include <iostream>
      using namespace std;
      int main() {
        return 0;
      }
  - type: folder
    name: developing
    content:
      - type: file
        name: simple_python.py
        content: |
          # 对许多初学者来说的第一个 Python 程序！
          print("Hello, World!")
      - type: folder
        name: folder_in_folder
        content:
          - type: file
            name: inner_file.py
            content: |
              # 文件夹中的文件夹里的内部文件
              import json
              import requests
          - type: folder
            name: inner_folder
            content: []
  - type: folder
    name: empty_folder
    content: []
  - type: file
    name: script.py
    content: |
      # 基本的 PyTorch 张量操作
      import torch
      import random
      
      x = torch.randn(2, 3, 4)
      y = x.transpose(1, 2)
      z = y.view(2, 12)
      print("z shape:", z.shape)