# @package apps.code_editor

font_size: 12
font: "Arial"
fontcolor: "#000000"
primary_button_color: "#ffffff"
secondary_button_color: "#ffffff"
danger_button_color: "#ffffff"
textarea_background_color: "#ffffff"

theme: "monokai"
mode: "python"
highlight: False
sort_feature: True

list_of_modes: 
  - python
  - javascript
  - css
  - yaml
  - markdown
  - shell
  - clike
  - go
list_of_themes: 
  - monokai