# @package apps.code_editor

font_size: 12
font: "Arial"
fontcolor: ""
primary_button_color: "#DC267F"
secondary_button_color: "#DC267F"
danger_button_color: "#FE6100"
textarea_background_color: "#FFFFFF"
main_background_color: "#648FFF"

theme: "monokai"
mode: "python"
highlight: False
sort_feature: True
list_of_modes: 
  - python
  - javascript
  - css
  - yaml
  - markdown
  - shell
  - clike
  - go
list_of_themes: 
  - monokai
  - eclipse
  - solarized
  - seti
  - night
  - dracula
  - twilight
  - zenburn
  - material