"""
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.
This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
"""

"""
Generate config/tasks/user_goal_variations_with_context.yaml.

For every goal variation in ``user_goal_variations.yaml`` whose underlying
high-level task has a reviewed context in ``task_contexts.yaml``, emit a
``<variation_key>__with_context`` entry that copies the variation verbatim
(its reworded goal + goal_style + reward fields) and attaches the SAME context
as the base task.

Why reuse the base context rather than write a new one per variation? The
context motivates the *task*, which is identical across the 9 phrasings of a
variation — only the goal wording changes. Sharing the already-reviewed
context keeps 153 entries consistent and maintainable, and preserves the
goal-variation study's single moving part (the phrasing).

Navigation variations are skipped: their base tasks have no context (a
preceding conversation adds nothing to a pure "open app X" action).

Run:
    uv run scripts/generate_goal_variation_contexts.py
"""

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
TASKS_DIR = REPO_ROOT / "config" / "tasks"
VARIATIONS = TASKS_DIR / "user_goal_variations.yaml"
CONTEXTS = TASKS_DIR / "task_contexts.yaml"
OUT = TASKS_DIR / "user_goal_variations_with_context.yaml"

CONTEXT_SUFFIX = "__with_context"
# Trailing "__<style>_<n>" tag on a variation key.
_STYLE_TAG = re.compile(r"__(?:casual|formal|unrelated_context)_\d+$")

HEADER = """\
# Goal variations WITH context. Auto-generated by
# scripts/generate_goal_variation_contexts.py — do not hand-edit; re-run the
# generator instead.
#
# For each goal variation whose base task has a reviewed context in
# task_contexts.yaml, this attaches that base context (the conversation that
# precedes and motivates the goal) to the variation. All non-context fields
# are copied verbatim from user_goal_variations.yaml, so reward semantics are
# identical; only the surrounding conversation is added.
#
# Key convention: <original_key>__<style>_<n>__with_context.
# Navigation variations are intentionally absent (their base tasks carry no
# context). Composed into all_tasks.yaml via its `defaults` list.
"""


class _LiteralDumper(yaml.SafeDumper):
    """Dumper that renders multi-line strings as ``|`` block scalars."""


def _str_representer(dumper: yaml.SafeDumper, data: str):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_LiteralDumper.add_representer(str, _str_representer)


def _base_key(variation_key: str) -> str:
    return _STYLE_TAG.sub("", variation_key)


def main() -> None:
    variations = yaml.safe_load(VARIATIONS.read_text())
    contexts = yaml.safe_load(CONTEXTS.read_text())

    # base task key -> its context string
    base_context = {
        k[: -len(CONTEXT_SUFFIX)]: v["context"]
        for k, v in contexts.items()
        if k.endswith(CONTEXT_SUFFIX)
    }

    out: dict[str, dict] = {}
    skipped_bases: set[str] = set()
    for key, cfg in variations.items():
        base = _base_key(key)
        context = base_context.get(base)
        if context is None:
            skipped_bases.add(base)
            continue
        entry = dict(cfg)  # verbatim copy of the variation's fields
        entry["context"] = context
        out[f"{key}{CONTEXT_SUFFIX}"] = entry

    body = yaml.dump(
        out, Dumper=_LiteralDumper, sort_keys=False, default_flow_style=False,
        allow_unicode=True, width=1000,
    )
    OUT.write_text(HEADER + "\n" + body)

    print(f"Wrote {len(out)} entries to {OUT.relative_to(REPO_ROOT)}")
    if skipped_bases:
        print(f"Skipped {len(skipped_bases)} base task(s) without context: "
              f"{', '.join(sorted(skipped_bases))}")


if __name__ == "__main__":
    main()
