# @package apps.todo
defaults:
  - default

init_todos: # left the ones we will use in tasks in English and translated the other ones to German
  - ["Oma besuchen", false]
  - ["Medizinische Unterlagen sortieren", false]
  - ["Mahlzeiten f체r die Woche planen", false]
  - ["Arzttermin bessorgen", true]
  - ["Buy groceries", false]
  - ["Tante Lisa anrufen", true]
  - ["Budget 체berpr체fen", false]
  - ["Wohnzimmer aufr채umen", true]
  - ["20 Minuten spazieren gehen", false]
  - ["30 Minuten meditieren", false]
  - ["Update calendar", false]
  - ["Answer emails", false]
  - ["Water plants", true]
  - ["Make fruit salad", false]
  - ["Vor dem Schlafengehen lesen", false]