# @package apps.todo
defaults:
  - default


+init_todos:
  - ["Visit a museum", false]
  - ["Organize the junk drawer", true]
  - ["Go for a bike ride", false]
  - ["Bake bread from scratch", false]
  - ["Research a new hobby", true]
  - ["Write a thank you note", false]
  - ["Clean out the fridge", false]
  - ["Watch a documentary", true]
  - ["Create a new playlist", false]
  - ["Donate old clothes", false]
  - ["Change bedsheets", true]
  - ["Read a chapter of a book", false]
  - ["Learn a new word", false]
  - ["Do a 15-minute stretch", false]
  - ["Call an old friend", true]
  - ["Meal prep for tomorrow", false]
  - ["Update your resume", false]
  - ["Take a plant cutting", false]
  - ["Tackle a small home repair", true]
  - ["Write a short story", false]
  - ["Plan a weekend trip", false]
  - ["Clean windows", false]
  - ["Try a new recipe", true]
  - ["Listen to a podcast", false]
  - ["Water the garden", false]
  - ["Journal for 10 minutes", true]
  - ["Mend a piece of clothing", false]
  - ["Delete old photos from your phone", false]
  - ["Schedule a dental cleaning", true]
  - ["Do a puzzle", false]
  - ["Go to the farmer's market", false]
  - ["Wash the car", false]
  - ["Wipe down kitchen cabinets", false]
  - ["Find a volunteer opportunity", false]
  - ["Plan a date night", true]
  - ["Learn a few phrases in hindi", false]
  - ["Back up your computer files", false]
  - ["Practice a musical instrument", false]
  - ["Take a new walking route", false]
  - ["Research investment options", true]
  - ["Fix a squeaky door", false]
  - ["Do a digital detox for one hour", false]
  - ["Visit a local park you haven't been to", true]
  - ["Sort mail and documents", false]
  - ["Review your monthly budget", false]
  - ["Floss your teeth", true]
  - ["Create a photo album", false]
  - ["Polish wooden furniture", false]
  - ["Unsubscribe from junk emails", true]
  - ["Write a positive review for a small business", false]