# @package apps.todo
defaults:
  - default

init_todos: # left the ones we will use in tasks in English and translated the other ones to Chinese
  - ["去看奶奶", false]
  - ["整理医疗论文", false]
  - ["计划本周的食谱", false]
  - ["预约医生", true]
  - ["Buy groceries", false]
  - ["给丽莎阿姨打电话", true]
  - ["检查预算", false]
  - ["整理客厅", true]
  - ["散步20分钟", false]
  - ["冥想30分钟", false]
  - ["Update calendar", false]
  - ["Answer emails", false]
  - ["Water plants", true]
  - ["Make fruit salad", false]
  - ["睡前阅读", false]