pop_up1:
  title: ${apps.start_page.headline}
  content: |
    这六个应用程序共同构成了一套强大的工具，方便帮助您的日常生活、工作和与他人的沟通。待办事项列表和日历让您的日程井然有序、保证进度按计划进行，确保不会错过任何任务或约会。地图服务帮助您在周边环境中导航，提供路线指引和实时更新，让您高效地到达目的地。对于程序员来说，代码编辑器通过实用功能和集成简化了开发流程，让您的创意更容易实现。在线商店为您提供了随时随地浏览和购买商品或服务的便捷方式，节省时间和精力。最后，即时通讯工具让您与朋友、家人和同事保持联系，实现实时沟通与协作。通过结合使用这些应用，您可以提升生产力，享受更加互联高效的生活方式。
  button_title: "明白了！开始吧！"
  position: "top right" # 选项：top, bottom, left, right, center 及其组合
  url_extension: "" # 目前尚未启用
  link_button_title: null # 没有可能误导用户的按钮
  link_button_url: null 
  image_url: null