# @package apps.onlineshop

allowed_credit_cards:
  - 'Visa'
  - 'MasterCard'
  # - 'Amex'
enable_credit_card_check: false
enable: False


font_family: 'Arial'
base_font_size: '16px'
font_color: '#000000'
background_color: '#FFFFFF'
button_background_color: '#FFFFFF'
button_font_color: '#000000'
highlight_font_color: '#000000'